### ISSUE TITLE
Difficulty to install with different Python Version [ 3.8 / 3.9 / 3.10]

### ISSUE THREAD

**Issue by EuphoriaLux** [Tonic-AI/Poly#1]
I am curious as to why there are numerous dependencies listed in the requirements.txt file, many of which, in my opinion, do not seem to be in use currently. Could this be accurate?

**Comment by Josephrp** [comment]
this standalone repo will be updated very soon, in the meantime you can try PolyGPT-Alpha using the autogpt-forge submission repository [here: https://github.com/Tonic-AI/AutoGPT/tree/master/autogpts/PolyGPT-alpha](https://github.com/Tonic-AI/AutoGPT/tree/master/autogpts/PolyGPT-alpha)

It wont be more than a few days until this is updated and things much more clarified, in fact we'll be testing things out soon, and you're welcome to join us
